gdc-manifest: gdc_manifest_20171012_060907.txt

runs:
  simulated-bwa:
    mapper: bwa
    dataset: simulated
    ref: hg18
    purity: 0.75
  COLO_829-GSC:
    dataset: COLO_829-GSC
    mapper: bwa
    ref: hg38
    purity: 1.0
  COLO_829-EBI:
    dataset: COLO_829-EBI
    mapper: bwa
    ref: hg38
    purity: 1.0
  COLO_829-TGen:
    dataset: COLO_829-TGen
    mapper: bwa
    ref: hg38
    purity: 1.0
  COLO_829-Ill:
    dataset: COLO_829-Ill
    mapper: bwa
    ref: hg38
    purity: 1.0

  TCGA-44-4112-1-bwa:
    mapper: bwa
    ref: hg38
    purity: 1.0
    dataset: TCGA-44-4112-1
    params:
      strelka: --exome
      manta: --exome
  TCGA-44-4112-2-bwa:
    mapper: bwa
    ref: hg38
    purity: 1.0
    dataset: TCGA-44-4112-2
    params:
      strelka: --exome
      manta: --exome
  TCGA-44-4112-3-bwa:
    mapper: bwa
    ref: hg38
    purity: 1.0
    dataset: TCGA-44-4112-3
    params:
      strelka: --exome
      manta: --exome
  TCGA-44-4112-4-bwa:
    mapper: bwa
    ref: hg38
    purity: 1.0
    dataset: TCGA-44-4112-4
    params:
      strelka: --exome
      manta: --exome
  TCGA-BL-A13J-1-bwa:
    mapper: bwa
    ref: hg38
    purity: 1.0
    dataset: TCGA-BL-A13J-1
    params:
      strelka: --exome
      manta: --exome
  TCGA-BL-A13J-2-bwa:
    mapper: bwa
    ref: hg38
    purity: 1.0
    dataset: TCGA-BL-A13J-2
    params:
      strelka: --exome
      manta: --exome


datasets:
  simulated:
    tumor:
      bam: ../data/hiseq.Cancer80.wholegenome.bwamemm.cat.sorted.smtag.bam
      name: Cancer80
    normal:
      bam: ../data/hiseq.Control.wholegenome.cov30.bwamemm.sorted.smtag.bam
      name: Control
    isize:
      mean: 312
      sd: 15
    truth: ../data/simulated-truth.indels.vcf
  COLO_829-GSC:
    tumor:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001226259_COLO_829_BCGSC_BCGSCPipe.bam
      name: Cancer
    normal:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001226245_COLO_829BL_BCGSC_BCGSCPipe.bam
      name: Control
    case: COLO_829
  COLO_829-EBI:
    tumor:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001226269_COLO_829_EPleasance_BCGSCPipe.bam
      name: Cancer
    normal:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001226254_COLO_829BL_EPleasance_BCGSCPipe.bam
      name: Control
    case: COLO_829
  COLO_829-Ill:
    tumor:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001226270_COLO_829_Illumina_BCGSCPipe.bam
      name: Cancer
    normal:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001226256_COLO_829BL_Illumina_BCGSCPipe.bam
      name: Control
    case: COLO_829
  COLO_829-TGen:
    tumor:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001229972_COLO_829_TGEN_BCGSCPipe.bam
      name: Cancer
    normal:
      bam: ../data/EGAD00001002142/EGAD00001002142/EGAZ00001226249_COLO_829BL_TGEN_BCGSCPipe.bam
      name: Control
    case: COLO_829
  TCGA-44-4112-1:
    type: Lung Adenocarcinoma
    sex: female
    tumor:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-01A-01D-1105-08.5_gdc_realn.bam
    normal:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-11A-01D-1105-08.12_gdc_realn.bam
    case: TCGA-44-4112
  TCGA-44-4112-2:
    type: Lung Adenocarcinoma
    sex: female
    tumor:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-01A-01D-1458-08.6_gdc_realn.bam
    normal:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-11A-21D-A27T-08.2_gdc_realn.bam
    case: TCGA-44-4112
  TCGA-44-4112-3:
    type: Lung Adenocarcinoma
    sex: female
    tumor:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-01A-01D-A271-08.5_gdc_realn.bam
    normal:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-11A-31D-A27T-08.2_gdc_realn.bam
    case: TCGA-44-4112
  TCGA-44-4112-4:
    type: Lung Adenocarcinoma
    sex: female
    tumor:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-01A-22D-A27T-08.2_gdc_realn.bam
    normal:
      bam: ../data/tcga/bams/C347.TCGA-44-4112-11A-01D-1105-08.12_gdc_realn.bam
    case: TCGA-44-4112
  TCGA-BL-A13J-1:
    type: Bladder Urothelial Carcinoma
    sex: male
    tumor:
      bam: ../data/tcga/bams/C500.TCGA-BL-A13J-01A-11D-A10S-08.7_gdc_realn.bam
    normal:
      bam: ../data/tcga/bams/C500.TCGA-BL-A13J-10A-01D-A10S-08.7_gdc_realn.bam
    case: TCGA-BL-A13J
  TCGA-BL-A13J-2:
    type: Bladder Urothelial Carcinoma
    sex: male
    tumor:
      bam: ../data/tcga/bams/C500.TCGA-BL-A13J-01A-11D-A271-08.2_gdc_realn.bam
    normal:
      bam: ../data/tcga/bams/C500.TCGA-BL-A13J-10A-01D-A271-08.2_gdc_realn.bam
    case: TCGA-BL-A13J

ref:
  hg18:
    fasta: ../data/hg18.fasta
    date: 2006-03
    chrom_prefix: chr
  hg38:
    fasta: ../data/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    date: 2013-12
    chrom_prefix: ""
    exons: resources/hg38.exons.bed

caller:
  delly:
    params: ""
    adhoc: true
    genotypes: true
    info:
      - END
      - SOMATIC
      - SVLEN
      - SVTYPE
  #pindel:
  #  params: "-M 1 -B 10000 -H 10 -x 4 -I false -a 2"
  lancet:
    params: ""
    score: QUAL
    invert: true
    adhoc: true
    genotypes: true
    info:
      - SOMATIC
      - SVLEN
      - SVTYPE
  manta:
    params: ""
    score: SOMATICSCORE
    invert: true
    adhoc: true
    useraw: true
    info:
      - SOMATIC
      - SOMATICSCORE
      - SVLEN
      - SVTYPE
  strelka:
    params: ""
    score: QSI
    invert: true
    adhoc: true
    info:
      - SOMATIC
      - QSI
  bpi:
    params: ""
    adhoc: true
    info:
      - SOMATIC
      - SVLEN
      - SVTYPE
  varlociraptor:
    params: "--indel-window 64 --omit-snvs"
    blacklist:
      - bpi
    score: PROB_SOMATIC_TUMOR
    genotypes: false
    info:
      - PROB_SOMATIC_TUMOR
      - PROB_GERMLINE_HET
      - PROB_GERMLINE_HOM
      - PROB_ABSENT
      - PROB_SOMATIC_NORMAL
      - PROB_ARTIFACT
      - SVLEN
    fmt:
      - AF
      - DP

vcf-match-params: "--max-dist 50 --max-len-diff 50"

len-ranges:
  DEL:
    - [1, 30]
    - [30, 50]
    - [50, 100]
    - [100, 250]
  INS:
    - [1, 30]
    - [30, 100]


depth-ranges:
  DEL:
    - [1, 20]
    - [20, 40]
  INS:
    - [1, 10]
    - [10, 20]
    - [20, 40]
    - [40, 100]


plots:
  concordance:
    colo1:
      - COLO_829-GSC
      - COLO_829-Ill
      - COLO_829-TGen
      - COLO_829-EBI
    #TCGA-44-4112-1:
    #  - TCGA-44-4112-1-bwa
    #  - TCGA-44-4112-2-bwa
    #TCGA-44-4112-2:
    #  - TCGA-44-4112-3-bwa
    #  - TCGA-44-4112-4-bwa
    #TCGA-BL-A13J:
    #  - TCGA-BL-A13J-1-bwa
    #  - TCGA-BL-A13J-2-bwa
    #control:
    #  - TCGA-BL-A13J-1-bwa
    #  - TCGA-BL-A13J-1-bwa
  known-truth:
    - simulated-bwa
