gdc-manifest: gdc_manifest_20171012_060907.txt

runs:
  simulated-qtip:
    mapper: qtip
    dataset: simulated
    ref: hg18
  simulated-bowtie:
    mapper: bowtie
    dataset: simulated
    ref: hg18

datasets:
  simulated:
    tumor:
      bam: /export/scratch2/structvar/vaf-experiments/aln/bwamemm/hiseq.Cancer80.wholegenome.bwamemm.cat.sorted.smtag.bam
      name: Cancer80
    normal:
      bam: /export/scratch2/structvar/vaf-experiments/aln/bwamemm/hiseq.Control.wholegenome.cov30.bwamemm.sorted.smtag.bam
      name: Control
    isize-mean: 312
    isize-sd: 15
  test:
    tumor:
      bam: .test/tumor.bam
      name: Cancer80
    normal:
      bam: .test/normal.bam
      name: Control
    isize-mean: 312
    isize-sd: 15

ref:
  hg18:
    index: ftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg18.zip
    date: 2006-03
  hg38:
    index: ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_genbank/Eukaryotes/vertebrates_mammals/Homo_sapiens/GRCh38/seqs_for_alignment_pipelines/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.bowtie_index.tar.gz
    date: 2013-12

caller:
  delly:
    params: ""
  pindel:
    params: ""
