gdc-manifest: gdc_manifest_20171012_060907.txt


datasets:
  simulated:
    tumor: /export/scratch2/structvar/vaf-experiments/aln/bwamemm/hiseq.Cancer80.wholegenome.bwamemm.cat.sorted.smtag.bam
    normal: /export/scratch2/structvar/vaf-experiments/aln/bwamemm/hiseq.Control.wholegenome.cov30.bwamemm.sorted.smtag.bam
    isize-mean: 312
    isize-sd: 15

ref:
  index: ftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg19.zipftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg19.zipftp://ftp.ccb.jhu.edu/pub/data/bowtie2_indexes/hg19.zip
