gdc-manifest: gdc_manifest_20171012_060907.txt

runs:
  #simulated-qtip:
  #  mapper: qtip
  #  dataset: simulated
  #  ref: hg18
  #  purity: [0.75]
  simulated-bwa:
    mapper: bwa
    dataset: simulated
    ref: hg18
    purity: [0.75]
  test:
    mapper: qtip
    dataset: test
    ref: hg18
    purity: [0.75]

datasets:
  simulated:
    tumor:
      bam: /export/scratch2/structvar/vaf-experiments/aln/bwamemm/hiseq.Cancer80.wholegenome.bwamemm.cat.sorted.smtag.bam
      name: Cancer80
    normal:
      bam: /export/scratch2/structvar/vaf-experiments/aln/bwamemm/hiseq.Control.wholegenome.cov30.bwamemm.sorted.smtag.bam
      name: Control
    isize:
      mean: 312
      sd: 15
  test:
    tumor:
      bam: .test/tumor.bam
      name: Cancer80
    normal:
      bam: .test/normal.bam
      name: Control
    isize:
      mean: 312
      sd: 15

ref:
  hg18:
    fasta: /export/scratch2/koster/data/ref/hg18.fasta
    date: 2006-03
  hg38:
    fasta: "TODO"
    date: 2013-12

caller:
  delly:
    params: "--exclusive-end"
  pindel:
    params: "-M 1 -B 10000 -H 10 -x 4 -I false -a 2"
  lancet:
    params: ""
  prosic:
    params: "--pileup-window 342 --omit-snvs --flat-priors --adjust-mapq --indel-window 20"
