gdc-manifest: gdc_manifest_20171012_060907.txt

runs:
  simulated-qtip:
    mapper: qtip
    dataset: simulated
    ref: hg18
    purity: [0.75]
  simulated-bwa:
    mapper: bwa
    dataset: simulated
    ref: hg18
    purity: [0.75]
  test:
    mapper: qtip
    dataset: test
    ref: hg18
    purity: [0.75]

datasets:
  simulated:
    tumor:
      bam: ../data/hiseq.Cancer80.wholegenome.bwamemm.cat.sorted.smtag.bam
      name: Cancer80
    normal:
      bam: ../data/hiseq.Control.wholegenome.cov30.bwamemm.sorted.smtag.bam
      name: Control
    isize:
      mean: 312
      sd: 15
    truth: ../data/simulated-truth.indels.vcf
  test:
    tumor:
      bam: .test/tumor.bam
      name: Cancer80
    normal:
      bam: .test/normal.bam
      name: Control
    isize:
      mean: 312
      sd: 15

ref:
  hg18:
    fasta: ../data/hg18.fasta
    date: 2006-03
    chrom_prefix: chr
  hg38:
    fasta: "TODO"
    date: 2013-12

caller:
  delly:
    params: ""
    adhoc: true
    filter: SOMATIC
    info:
      - END
      - SOMATIC
  #pindel:
  #  params: "-M 1 -B 10000 -H 10 -x 4 -I false -a 2"
  lancet:
    params: ""
    score: QUAL
    invert: true
    filter: SOMATIC
    adhoc: true
    info:
      - SOMATIC
  prosic:
    params: "--pileup-window 342 --flat-priors --adjust-mapq --indel-window 100 --max-indel-overlap 25"
    delly: "--exclusive-end"
    score: PROB_SOMATIC
    info:
      - PROB_SOMATIC
      - PROB_GERMLINE
      - PROB_ABSENT
      - CASE_AF
      - CONTROL_AF

vcf-match-params: "--max-dist 50 --max-len-diff 10"

len-ranges:
  - [1, 30]
  - [30, 50]
  - [50, 70]
  - [70, 100]
  - [100, 150]
  - [150, 250]
